name: Public Docker Image

on:
  push:
    branches: ['main']

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4  
      -
        name: Build Docker Image
        run: docker build -t lucadecastro/tmaior-chat-image:latest -f Dockerfile .
      -
        name: Tag Docker Image
        run: docker tag lucadecastro/tmaior-chat-image:latest lucadecastro/tmaior-chat-image:v1
      -
        name: Push Docker Image to Docker Hub
        run:  |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lucadecastro/tmaior-chat-image:v1
      -
        name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@"${{ secrets.EC2_HOST }}" <<EOF
            docker stop tmaior-chat-app-container
            docker pull lucadecastro/tmaior-chat-image:latest
            docker run -d --name tmaior-chat-app-container -p 80:80 lucadecastro/tmaior-chat-image:v1
            EOF
          rm private_key.pem
