name: Public Docker Image

on:
  push:
    branches: ['main']

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4  
      -
        name: Build Docker Image
        run: docker build -t lucadecastro/tmaior-chat-image:latest -f Dockerfile .
      -
        name: Tag Docker Image
        run: docker tag lucadecastro/tmaior-chat-image:latest lucadecastro/tmaior-chat-image:v1
      -
        name: Push Docker Image to Docker Hub
        run:  |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lucadecastro/tmaior-chat-image:v1
      -
        name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@"${{ secrets.EC2_HOST }}" <<EOF
            if [ \$(docker ps -aqf "name=tmaior-chat-app-container") ]; then
              docker stop tmaior-chat-app-container
              docker rm tmaior-chat-app-container
            fi
            docker pull lucadecastro/tmaior-chat-image:latest
            docker run -d --name tmaior-chat-app-container -p 80:80 lucadecastro/tmaior-chat-image:v1
          EOF
